# Generated by Django 3.2.19 on 2023-06-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='q11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question11', to='Template.questions'),
        ),
        migrations.AddField(
            model_name='template',
            name='q12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question12', to='Template.questions'),
        ),
        migrations.AddField(
            model_name='template',
            name='q13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question13', to='Template.questions'),
        ),
        migrations.AddField(
            model_name='template',
            name='q14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question14', to='Template.questions'),
        ),
        migrations.AddField(
            model_name='template',
            name='q15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question15', to='Template.questions'),
        ),
        migrations.AddField(
            model_name='template',
            name='q16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question16', to='Template.questions'),
        ),
        migrations.AddField(
            model_name='template',
            name='q17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question17', to='Template.questions'),
        ),
    ]
