# Generated by Django 3.2.19 on 2023-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0003_alter_template_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
    ]
