# Generated by Django 3.2.19 on 2023-06-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_diarymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
