# Generated by Django 3.2.19 on 2023-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_diarymodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
