# Generated by Django 3.2.19 on 2023-06-20 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Slambook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slambooktemplate',
            name='answers',
            field=models.ManyToManyField(blank=True, to='Slambook.AnswersTemplate'),
        ),
        migrations.AlterField(
            model_name='answerstemplate',
            name='filled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.usermodel'),
        ),
    ]
