# Generated by Django 3.2.19 on 2023-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slambook', '0002_auto_20230620_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slambooktemplate',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='Slambook.AnswersTemplate'),
        ),
    ]
